CREATE DATABASE IF NOT EXISTS khoobrooz
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE khoobrooz;

CREATE TABLE IF NOT EXISTS menus (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  url VARCHAR(600) NULL,
  slug VARCHAR(180) NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT chk_menus_accuracy CHECK (accuracy IN (0, 1, 2)),
  CONSTRAINT fk_menus_parent FOREIGN KEY (parent_id) REFERENCES menus(id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  type VARCHAR(60) NOT NULL DEFAULT 'encyclopedia',
  locale VARCHAR(10) NOT NULL DEFAULT 'fa',
  summary VARCHAR(800) NULL,
  content_top LONGTEXT NULL,
  content_bottom LONGTEXT NULL,
  cover_image_url VARCHAR(600) NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  canonical_url VARCHAR(600) NULL,
  faq_json JSON NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  is_indexable TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY uq_categories_locale_slug (locale, slug),
  CONSTRAINT chk_categories_accuracy CHECK (accuracy IN (0, 1, 2)),
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  body LONGTEXT NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL,
  published_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT chk_tags_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS services (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  locale VARCHAR(10) NOT NULL DEFAULT 'fa',
  slug VARCHAR(180) NOT NULL,
  title VARCHAR(220) NOT NULL,
  short_title VARCHAR(120) NULL,
  summary VARCHAR(800) NULL,
  body LONGTEXT NULL,
  icon VARCHAR(150) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL,
  published_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY uq_services_locale_slug (locale, slug),
  CONSTRAINT chk_services_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS articles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT UNSIGNED NULL,
  locale VARCHAR(10) NOT NULL DEFAULT 'fa',
  title VARCHAR(240) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  excerpt VARCHAR(900) NULL,
  body LONGTEXT NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  approve TINYINT(1) NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL,
  published_by BIGINT UNSIGNED NULL,
  scheduled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY uq_articles_locale_slug (locale, slug),
  CONSTRAINT fk_articles_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT chk_articles_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS article_tag (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  article_id BIGINT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uq_article_tag (article_id, tag_id),
  CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES articles(id),
  CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tags(id),
  CONSTRAINT chk_article_tag_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT UNSIGNED NULL,
  locale VARCHAR(10) NOT NULL DEFAULT 'fa',
  title VARCHAR(240) NOT NULL,
  slug VARCHAR(200) NOT NULL,
  summary VARCHAR(900) NULL,
  body LONGTEXT NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  approve TINYINT(1) NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL,
  published_by BIGINT UNSIGNED NULL,
  scheduled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE KEY uq_news_locale_slug (locale, slug),
  CONSTRAINT fk_news_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT chk_news_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS news_tag (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  news_id BIGINT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uq_news_tag (news_id, tag_id),
  CONSTRAINT fk_news_tag_news FOREIGN KEY (news_id) REFERENCES news(id),
  CONSTRAINT fk_news_tag_tag FOREIGN KEY (tag_id) REFERENCES tags(id),
  CONSTRAINT chk_news_tag_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS content_sources (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(220) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  website_url VARCHAR(600) NOT NULL,
  feed_url VARCHAR(600) NULL,
  source_type ENUM('rss', 'atom', 'api', 'scraper', 'manual') NOT NULL DEFAULT 'manual',
  source_category ENUM('official', 'news_agency', 'trade_media', 'international') NOT NULL DEFAULT 'official',
  language VARCHAR(10) NOT NULL DEFAULT 'fa',
  country VARCHAR(80) NULL,
  default_article_type ENUM('news', 'circular', 'regulation', 'official_notice') NOT NULL DEFAULT 'news',
  default_category_id BIGINT UNSIGNED NULL,
  trust_level ENUM('official', 'high', 'medium', 'low') NOT NULL DEFAULT 'medium',
  fetch_interval_minutes INT UNSIGNED NOT NULL DEFAULT 60,
  backfill_days INT UNSIGNED NOT NULL DEFAULT 7,
  max_backfill_items INT UNSIGNED NOT NULL DEFAULT 20,
  requires_review TINYINT(1) NOT NULL DEFAULT 1,
  allow_auto_publish TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 0,
  respect_robots TINYINT(1) NOT NULL DEFAULT 1,
  connection_status ENUM('ready', 'needs_configuration', 'manual_required', 'disabled', 'error') NOT NULL DEFAULT 'needs_configuration',
  terms_notes TEXT NULL,
  parser_key VARCHAR(120) NULL,
  request_headers JSON NULL,
  last_fetched_at TIMESTAMP NULL,
  last_successful_fetch_at TIMESTAMP NULL,
  last_error_at TIMESTAMP NULL,
  last_error_message VARCHAR(900) NULL,
  etag VARCHAR(255) NULL,
  last_modified VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  KEY ix_content_sources_active_next (is_active, connection_status, last_fetched_at),
  CONSTRAINT fk_content_sources_category FOREIGN KEY (default_category_id) REFERENCES categories(id),
  CONSTRAINT chk_content_sources_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS source_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_id BIGINT UNSIGNED NOT NULL,
  external_id VARCHAR(255) NULL,
  guid VARCHAR(600) NULL,
  source_url VARCHAR(900) NOT NULL,
  original_title VARCHAR(500) NOT NULL,
  original_summary LONGTEXT NULL,
  original_content LONGTEXT NULL,
  original_image_url VARCHAR(900) NULL,
  original_author VARCHAR(220) NULL,
  original_language VARCHAR(10) NOT NULL DEFAULT 'fa',
  source_published_at TIMESTAMP NULL,
  source_updated_at TIMESTAMP NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content_hash CHAR(64) NOT NULL,
  normalized_title_hash CHAR(64) NOT NULL,
  detected_content_type ENUM('news', 'circular', 'regulation', 'official_notice') NOT NULL DEFAULT 'news',
  suggested_category_id BIGINT UNSIGNED NULL,
  relevance_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  processing_status ENUM('pending_review', 'approved', 'published', 'rejected', 'duplicate', 'archived', 'failed', 'filtered_out') NOT NULL DEFAULT 'pending_review',
  duplicate_of_id BIGINT UNSIGNED NULL,
  article_id BIGINT UNSIGNED NULL,
  news_id BIGINT UNSIGNED NULL,
  circular_number VARCHAR(180) NULL,
  issuer VARCHAR(220) NULL,
  issued_at TIMESTAMP NULL,
  effective_at TIMESTAMP NULL,
  subject VARCHAR(500) NULL,
  official_text LONGTEXT NULL,
  attachment_url VARCHAR(900) NULL,
  official_page_url VARCHAR(900) NULL,
  validity_status VARCHAR(120) NULL,
  supersedes_id BIGINT UNSIGNED NULL,
  amends_id BIGINT UNSIGNED NULL,
  last_verified_at TIMESTAMP NULL,
  raw_payload JSON NULL,
  fetch_metadata JSON NULL,
  title VARCHAR(500) NULL,
  slug VARCHAR(240) NULL,
  summary LONGTEXT NULL,
  body LONGTEXT NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(500) NULL,
  selected_image_url VARCHAR(900) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uq_source_items_source_guid (source_id, guid),
  UNIQUE KEY uq_source_items_source_url (source_id, source_url),
  KEY ix_source_items_status_type (processing_status, detected_content_type, fetched_at),
  KEY ix_source_items_hash (content_hash, normalized_title_hash),
  CONSTRAINT fk_source_items_source FOREIGN KEY (source_id) REFERENCES content_sources(id),
  CONSTRAINT fk_source_items_category FOREIGN KEY (suggested_category_id) REFERENCES categories(id),
  CONSTRAINT fk_source_items_duplicate FOREIGN KEY (duplicate_of_id) REFERENCES source_items(id),
  CONSTRAINT fk_source_items_article FOREIGN KEY (article_id) REFERENCES articles(id),
  CONSTRAINT fk_source_items_news FOREIGN KEY (news_id) REFERENCES news(id),
  CONSTRAINT fk_source_items_supersedes FOREIGN KEY (supersedes_id) REFERENCES source_items(id),
  CONSTRAINT fk_source_items_amends FOREIGN KEY (amends_id) REFERENCES source_items(id),
  CONSTRAINT chk_source_items_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS countries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name_fa VARCHAR(160) NOT NULL,
  name_en VARCHAR(160) NOT NULL,
  iso2 CHAR(2) NOT NULL UNIQUE,
  iso3 CHAR(3) NOT NULL UNIQUE,
  phone_code VARCHAR(12) NULL,
  capital VARCHAR(160) NULL,
  continent VARCHAR(80) NULL,
  currency_code CHAR(3) NULL,
  timezone_default VARCHAR(120) NULL,
  flag VARCHAR(20) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  CONSTRAINT chk_countries_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS cities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  country_id BIGINT UNSIGNED NOT NULL,
  name_fa VARCHAR(160) NOT NULL,
  name_en VARCHAR(160) NOT NULL,
  timezone VARCHAR(120) NOT NULL,
  is_trade_city TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 1,
  UNIQUE KEY uq_cities_country_name (country_id, name_en),
  KEY ix_cities_country_sort (country_id, accuracy, sort_order),
  CONSTRAINT fk_cities_country FOREIGN KEY (country_id) REFERENCES countries(id),
  CONSTRAINT chk_cities_accuracy CHECK (accuracy IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS world_clock_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  country_id BIGINT UNSIGNED NULL,
  city_id BIGINT UNSIGNED NULL,
  city VARCHAR(160) NOT NULL,
  country VARCHAR(160) NOT NULL,
  country_code CHAR(2) NULL,
  timezone VARCHAR(120) NOT NULL,
  market_label VARCHAR(180) NULL,
  flag VARCHAR(20) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 0,
  published_at TIMESTAMP NULL,
  published_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED NULL,
  modified_at TIMESTAMP NULL,
  modified_by BIGINT UNSIGNED NULL,
  accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT fk_world_clock_country FOREIGN KEY (country_id) REFERENCES countries(id),
  CONSTRAINT fk_world_clock_city FOREIGN KEY (city_id) REFERENCES cities(id),
  CONSTRAINT chk_world_clock_accuracy CHECK (accuracy IN (0, 1, 2))
);
