/*
  Full countries seed data
  Target: SQL Server
  Source shape: name, capital, iso2, iso3
*/

USE khoobrooz;
GO

MERGE dbo.countries AS target
USING (VALUES
  (N'افغانستان', N'Afghanistan', N'AF', N'AFG', NULL, N'Kabul', NULL, NULL, N'AF', 10, 1),
  (N'جزایر آلاند', N'Aland Islands', N'AX', N'ALA', NULL, N'Mariehamn', NULL, NULL, N'AX', 20, 1),
  (N'آلبانی', N'Albania', N'AL', N'ALB', NULL, N'Tirana', NULL, NULL, N'AL', 30, 1),
  (N'الجزایر', N'Algeria', N'DZ', N'DZA', NULL, N'Algiers', NULL, NULL, N'DZ', 40, 1),
  (N'آندورا', N'Andorra', N'AD', N'AND', NULL, N'Andorra la Vella', NULL, NULL, N'AD', 50, 1),
  (N'آنگولا', N'Angola', N'AO', N'AGO', NULL, N'Luanda', NULL, NULL, N'AO', 60, 1),
  (N'آنگویلا', N'Anguilla', N'AI', N'AIA', NULL, N'The Valley', NULL, NULL, N'AI', 70, 1),
  (N'جنوبگان', N'Antarctica', N'AQ', N'ATA', NULL, NULL, NULL, NULL, N'AQ', 80, 1),
  (N'آنتیگوا و باربودا', N'Antigua and Barbuda', N'AG', N'ATG', NULL, N'St. John''s', NULL, NULL, N'AG', 90, 1),
  (N'آرژانتین', N'Argentina', N'AR', N'ARG', NULL, N'Buenos Aires', NULL, NULL, N'AR', 100, 1),
  (N'ارمنستان', N'Armenia', N'AM', N'ARM', NULL, N'Yerevan', NULL, NULL, N'AM', 110, 1),
  (N'آروبا', N'Aruba', N'AW', N'ABW', NULL, N'Oranjestad', NULL, NULL, N'AW', 120, 1),
  (N'استرالیا', N'Australia', N'AU', N'AUS', NULL, N'Canberra', NULL, NULL, N'AU', 130, 1),
  (N'اتریش', N'Austria', N'AT', N'AUT', NULL, N'Vienna', NULL, NULL, N'AT', 140, 1),
  (N'جمهوری آذربایجان', N'Azerbaijan', N'AZ', N'AZE', NULL, N'Baku', NULL, NULL, N'AZ', 150, 1),
  (N'باهاما', N'Bahamas', N'BS', N'BHS', NULL, N'Nassau', NULL, NULL, N'BS', 160, 1),
  (N'بحرین', N'Bahrain', N'BH', N'BHR', NULL, N'Manama', NULL, NULL, N'BH', 170, 1),
  (N'بنگلادش', N'Bangladesh', N'BD', N'BGD', NULL, N'Dhaka', NULL, NULL, N'BD', 180, 1),
  (N'باربادوس', N'Barbados', N'BB', N'BRB', NULL, N'Bridgetown', NULL, NULL, N'BB', 190, 1),
  (N'بلاروس', N'Belarus', N'BY', N'BLR', NULL, N'Minsk', NULL, NULL, N'BY', 200, 1),
  (N'بلژیک', N'Belgium', N'BE', N'BEL', NULL, N'Brussels', NULL, NULL, N'BE', 210, 1),
  (N'بلیز', N'Belize', N'BZ', N'BLZ', NULL, N'Belmopan', NULL, NULL, N'BZ', 220, 1),
  (N'بنین', N'Benin', N'BJ', N'BEN', NULL, N'Porto-Novo', NULL, NULL, N'BJ', 230, 1),
  (N'برمودا', N'Bermuda', N'BM', N'BMU', NULL, N'Hamilton', NULL, NULL, N'BM', 240, 1),
  (N'بوتان', N'Bhutan', N'BT', N'BTN', NULL, N'Thimphu', NULL, NULL, N'BT', 250, 1),
  (N'بولیوی', N'Bolivia', N'BO', N'BOL', NULL, N'Sucre', NULL, NULL, N'BO', 260, 1),
  (N'جزایر کارائیب هلند', N'Bonaire, Saint Eustatius and Saba ', N'BQ', N'BES', NULL, NULL, NULL, NULL, N'BQ', 270, 1),
  (N'بوسنی و هرزگوین', N'Bosnia and Herzegovina', N'BA', N'BIH', NULL, N'Sarajevo', NULL, NULL, N'BA', 280, 1),
  (N'بوتسوانا', N'Botswana', N'BW', N'BWA', NULL, N'Gaborone', NULL, NULL, N'BW', 290, 1),
  (N'جزیرهٔ بووه', N'Bouvet Island', N'BV', N'BVT', NULL, NULL, NULL, NULL, N'BV', 300, 1),
  (N'برزیل', N'Brazil', N'BR', N'BRA', NULL, N'Brasilia', NULL, NULL, N'BR', 310, 1),
  (N'قلمرو بریتانیا در اقیانوس هند', N'British Indian Ocean Territory', N'IO', N'IOT', NULL, N'Diego Garcia', NULL, NULL, N'IO', 320, 1),
  (N'جزایر ویرجین بریتانیا', N'British Virgin Islands', N'VG', N'VGB', NULL, N'Road Town', NULL, NULL, N'VG', 330, 1),
  (N'برونئی', N'Brunei', N'BN', N'BRN', NULL, N'Bandar Seri Begawan', NULL, NULL, N'BN', 340, 1),
  (N'بلغارستان', N'Bulgaria', N'BG', N'BGR', NULL, N'Sofia', NULL, NULL, N'BG', 350, 1),
  (N'بورکینافاسو', N'Burkina Faso', N'BF', N'BFA', NULL, N'Ouagadougou', NULL, NULL, N'BF', 360, 1),
  (N'بوروندی', N'Burundi', N'BI', N'BDI', NULL, N'Bujumbura', NULL, NULL, N'BI', 370, 1),
  (N'کامبوج', N'Cambodia', N'KH', N'KHM', NULL, N'Phnom Penh', NULL, NULL, N'KH', 380, 1),
  (N'کامرون', N'Cameroon', N'CM', N'CMR', NULL, N'Yaounde', NULL, NULL, N'CM', 390, 1),
  (N'کانادا', N'Canada', N'CA', N'CAN', NULL, N'Ottawa', NULL, NULL, N'CA', 400, 1),
  (N'کیپ‌ورد', N'Cape Verde', N'CV', N'CPV', NULL, N'Praia', NULL, NULL, N'CV', 410, 1),
  (N'جزایر کِیمن', N'Cayman Islands', N'KY', N'CYM', NULL, N'George Town', NULL, NULL, N'KY', 420, 1),
  (N'جمهوری افریقای مرکزی', N'Central African Republic', N'CF', N'CAF', NULL, N'Bangui', NULL, NULL, N'CF', 430, 1),
  (N'چاد', N'Chad', N'TD', N'TCD', NULL, N'N''Djamena', NULL, NULL, N'TD', 440, 1),
  (N'شیلی', N'Chile', N'CL', N'CHL', NULL, N'Santiago', NULL, NULL, N'CL', 450, 1),
  (N'چین', N'China', N'CN', N'CHN', NULL, N'Beijing', NULL, NULL, N'CN', 460, 1),
  (N'جزیرهٔ کریسمس', N'Christmas Island', N'CX', N'CXR', NULL, N'Flying Fish Cove', NULL, NULL, N'CX', 470, 1),
  (N'جزایر کوکوس', N'Cocos (Keeling) Islands', N'CC', N'CCK', NULL, N'West Island', NULL, NULL, N'CC', 480, 1),
  (N'کلمبیا', N'Colombia', N'CO', N'COL', NULL, N'Bogota', NULL, NULL, N'CO', 490, 1),
  (N'کومور', N'Comoros', N'KM', N'COM', NULL, N'Moroni', NULL, NULL, N'KM', 500, 1),
  (N'کنگو - برازویل', N'Congo', N'CG', N'COG', NULL, N'Brazzaville', NULL, NULL, N'CG', 510, 1),
  (N'جزایر کوک', N'Cook Islands', N'CK', N'COK', NULL, N'Avarua', NULL, NULL, N'CK', 520, 1),
  (N'کاستاریکا', N'Costa Rica', N'CR', N'CRI', NULL, N'San Jose', NULL, NULL, N'CR', 530, 1),
  (N'کرواسی', N'Croatia', N'HR', N'HRV', NULL, N'Zagreb', NULL, NULL, N'HR', 540, 1),
  (N'کوبا', N'Cuba', N'CU', N'CUB', NULL, N'Havana', NULL, NULL, N'CU', 550, 1),
  (N'کوراسائو', N'Curacao', N'CW', N'CUW', NULL, N' Willemstad', NULL, NULL, N'CW', 560, 1),
  (N'قبرس', N'Cyprus', N'CY', N'CYP', NULL, N'Nicosia', NULL, NULL, N'CY', 570, 1),
  (N'چک', N'Czech Republic', N'CZ', N'CZE', NULL, N'Prague', NULL, NULL, N'CZ', 580, 1),
  (N'کنگو - کینشاسا', N'Democratic Republic of the Congo', N'CD', N'COD', NULL, N'Kinshasa', NULL, NULL, N'CD', 590, 1),
  (N'دانمارک', N'Denmark', N'DK', N'DNK', NULL, N'Copenhagen', NULL, NULL, N'DK', 600, 1),
  (N'جیبوتی', N'Djibouti', N'DJ', N'DJI', NULL, N'Djibouti', NULL, NULL, N'DJ', 610, 1),
  (N'دومینیکا', N'Dominica', N'DM', N'DMA', NULL, N'Roseau', NULL, NULL, N'DM', 620, 1),
  (N'جمهوری دومینیکن', N'Dominican Republic', N'DO', N'DOM', NULL, N'Santo Domingo', NULL, NULL, N'DO', 630, 1),
  (N'اکوادور', N'Ecuador', N'EC', N'ECU', NULL, N'Quito', NULL, NULL, N'EC', 640, 1),
  (N'مصر', N'Egypt', N'EG', N'EGY', NULL, N'Cairo', NULL, NULL, N'EG', 650, 1),
  (N'السالوادور', N'El Salvador', N'SV', N'SLV', NULL, N'San Salvador', NULL, NULL, N'SV', 660, 1),
  (N'گینهٔ استوایی', N'Equatorial Guinea', N'GQ', N'GNQ', NULL, N'Malabo', NULL, NULL, N'GQ', 670, 1),
  (N'اریتره', N'Eritrea', N'ER', N'ERI', NULL, N'Asmara', NULL, NULL, N'ER', 680, 1),
  (N'استونی', N'Estonia', N'EE', N'EST', NULL, N'Tallinn', NULL, NULL, N'EE', 690, 1),
  (N'اتیوپی', N'Ethiopia', N'ET', N'ETH', NULL, N'Addis Ababa', NULL, NULL, N'ET', 700, 1),
  (N'جزایر فالکلند', N'Falkland Islands', N'FK', N'FLK', NULL, N'Stanley', NULL, NULL, N'FK', 710, 1),
  (N'جزایر فارو', N'Faroe Islands', N'FO', N'FRO', NULL, N'Torshavn', NULL, NULL, N'FO', 720, 1),
  (N'فیجی', N'Fiji', N'FJ', N'FJI', NULL, N'Suva', NULL, NULL, N'FJ', 730, 1),
  (N'فنلاند', N'Finland', N'FI', N'FIN', NULL, N'Helsinki', NULL, NULL, N'FI', 740, 1),
  (N'فرانسه', N'France', N'FR', N'FRA', NULL, N'Paris', NULL, NULL, N'FR', 750, 1),
  (N'پلی‌نزی فرانسه', N'French Polynesia', N'PF', N'PYF', NULL, N'Papeete', NULL, NULL, N'PF', 760, 1),
  (N'سرزمین‌های جنوبی فرانسه', N'French Southern Territories', N'TF', N'ATF', NULL, N'Port-aux-Francais', NULL, NULL, N'TF', 770, 1),
  (N'گابن', N'Gabon', N'GA', N'GAB', NULL, N'Libreville', NULL, NULL, N'GA', 780, 1),
  (N'گامبیا', N'Gambia', N'GM', N'GMB', NULL, N'Banjul', NULL, NULL, N'GM', 790, 1),
  (N'گرجستان', N'Georgia', N'GE', N'GEO', NULL, N'Tbilisi', NULL, NULL, N'GE', 800, 1),
  (N'آلمان', N'Germany', N'DE', N'DEU', NULL, N'Berlin', NULL, NULL, N'DE', 810, 1),
  (N'غنا', N'Ghana', N'GH', N'GHA', NULL, N'Accra', NULL, NULL, N'GH', 820, 1),
  (N'جبل‌الطارق', N'Gibraltar', N'GI', N'GIB', NULL, N'Gibraltar', NULL, NULL, N'GI', 830, 1),
  (N'یونان', N'Greece', N'GR', N'GRC', NULL, N'Athens', NULL, NULL, N'GR', 840, 1),
  (N'گرینلند', N'Greenland', N'GL', N'GRL', NULL, N'Nuuk', NULL, NULL, N'GL', 850, 1),
  (N'گرنادا', N'Grenada', N'GD', N'GRD', NULL, N'St. George''s', NULL, NULL, N'GD', 860, 1),
  (N'گوادلوپ', N'Guadeloupe', N'GP', N'GLP', NULL, N'Basse-Terre', NULL, NULL, N'GP', 870, 1),
  (N'گوام', N'Guam', N'GU', N'GUM', NULL, N'Hagatna', NULL, NULL, N'GU', 880, 1),
  (N'گواتمالا', N'Guatemala', N'GT', N'GTM', NULL, N'Guatemala City', NULL, NULL, N'GT', 890, 1),
  (N'گرنزی', N'Guernsey', N'GG', N'GGY', NULL, N'St Peter Port', NULL, NULL, N'GG', 900, 1),
  (N'گینه', N'Guinea', N'GN', N'GIN', NULL, N'Conakry', NULL, NULL, N'GN', 910, 1),
  (N'گینهٔ بیسائو', N'Guinea-Bissau', N'GW', N'GNB', NULL, N'Bissau', NULL, NULL, N'GW', 920, 1),
  (N'گویان', N'Guyana', N'GY', N'GUY', NULL, N'Georgetown', NULL, NULL, N'GY', 930, 1),
  (N'هائیتی', N'Haiti', N'HT', N'HTI', NULL, N'Port-au-Prince', NULL, NULL, N'HT', 940, 1),
  (N'هرد و جزایر مک‌دونالد', N'Heard Island and McDonald Islands', N'HM', N'HMD', NULL, NULL, NULL, NULL, N'HM', 950, 1),
  (N'هندوراس', N'Honduras', N'HN', N'HND', NULL, N'Tegucigalpa', NULL, NULL, N'HN', 960, 1),
  (N'هنگ‌کنگ، منطقهٔ ویژهٔ اداری چین', N'Hong Kong', N'HK', N'HKG', NULL, N'Hong Kong', NULL, NULL, N'HK', 970, 1),
  (N'مجارستان', N'Hungary', N'HU', N'HUN', NULL, N'Budapest', NULL, NULL, N'HU', 980, 1),
  (N'ایسلند', N'Iceland', N'IS', N'ISL', NULL, N'Reykjavik', NULL, NULL, N'IS', 990, 1),
  (N'هند', N'India', N'IN', N'IND', NULL, N'New Delhi', NULL, NULL, N'IN', 1000, 1),
  (N'اندونزی', N'Indonesia', N'ID', N'IDN', NULL, N'Jakarta', NULL, NULL, N'ID', 1010, 1),
  (N'ایران', N'Iran', N'IR', N'IRN', NULL, N'Tehran', NULL, NULL, N'IR', 1020, 1),
  (N'عراق', N'Iraq', N'IQ', N'IRQ', NULL, N'Baghdad', NULL, NULL, N'IQ', 1030, 1),
  (N'ایرلند', N'Ireland', N'IE', N'IRL', NULL, N'Dublin', NULL, NULL, N'IE', 1040, 1),
  (N'جزیرهٔ من', N'Isle of Man', N'IM', N'IMN', NULL, N'Douglas, Isle of Man', NULL, NULL, N'IM', 1050, 1),
  (N'اسرائیل', N'Israel', N'IL', N'ISR', NULL, N'Jerusalem', NULL, NULL, N'IL', 1060, 1),
  (N'ایتالیا', N'Italy', N'IT', N'ITA', NULL, N'Rome', NULL, NULL, N'IT', 1070, 1),
  (N'ساحل عاج', N'Ivory Coast', N'CI', N'CIV', NULL, N'Yamoussoukro', NULL, NULL, N'CI', 1080, 1),
  (N'جامائیکا', N'Jamaica', N'JM', N'JAM', NULL, N'Kingston', NULL, NULL, N'JM', 1090, 1),
  (N'ژاپن', N'Japan', N'JP', N'JPN', NULL, N'Tokyo', NULL, NULL, N'JP', 1100, 1),
  (N'جرزی', N'Jersey', N'JE', N'JEY', NULL, N'Saint Helier', NULL, NULL, N'JE', 1110, 1),
  (N'اردن', N'Jordan', N'JO', N'JOR', NULL, N'Amman', NULL, NULL, N'JO', 1120, 1),
  (N'قزاقستان', N'Kazakhstan', N'KZ', N'KAZ', NULL, N'Astana', NULL, NULL, N'KZ', 1130, 1),
  (N'کنیا', N'Kenya', N'KE', N'KEN', NULL, N'Nairobi', NULL, NULL, N'KE', 1140, 1),
  (N'کیریباتی', N'Kiribati', N'KI', N'KIR', NULL, N'Tarawa', NULL, NULL, N'KI', 1150, 1),
  (N'کوزوو', N'Kosovo', N'XK', N'XKX', NULL, N'Pristina', NULL, NULL, N'XK', 1160, 1),
  (N'کویت', N'Kuwait', N'KW', N'KWT', NULL, N'Kuwait City', NULL, NULL, N'KW', 1170, 1),
  (N'قرقیزستان', N'Kyrgyzstan', N'KG', N'KGZ', NULL, N'Bishkek', NULL, NULL, N'KG', 1180, 1),
  (N'لائوس', N'Laos', N'LA', N'LAO', NULL, N'Vientiane', NULL, NULL, N'LA', 1190, 1),
  (N'لتونی', N'Latvia', N'LV', N'LVA', NULL, N'Riga', NULL, NULL, N'LV', 1200, 1),
  (N'لبنان', N'Lebanon', N'LB', N'LBN', NULL, N'Beirut', NULL, NULL, N'LB', 1210, 1),
  (N'لسوتو', N'Lesotho', N'LS', N'LSO', NULL, N'Maseru', NULL, NULL, N'LS', 1220, 1),
  (N'لیبریا', N'Liberia', N'LR', N'LBR', NULL, N'Monrovia', NULL, NULL, N'LR', 1230, 1),
  (N'لیبی', N'Libya', N'LY', N'LBY', NULL, N'Tripolis', NULL, NULL, N'LY', 1240, 1),
  (N'لیختن‌اشتاین', N'Liechtenstein', N'LI', N'LIE', NULL, N'Vaduz', NULL, NULL, N'LI', 1250, 1),
  (N'لیتوانی', N'Lithuania', N'LT', N'LTU', NULL, N'Vilnius', NULL, NULL, N'LT', 1260, 1),
  (N'لوکزامبورگ', N'Luxembourg', N'LU', N'LUX', NULL, N'Luxembourg', NULL, NULL, N'LU', 1270, 1),
  (N'ماکائو، منطقهٔ ویژهٔ اداری چین', N'Macau', N'MO', N'MAC', NULL, N'Macao', NULL, NULL, N'MO', 1280, 1),
  (N'مقدونیهٔ شمالی', N'Macedonia', N'MK', N'MKD', NULL, N'Skopje', NULL, NULL, N'MK', 1290, 1),
  (N'ماداگاسکار', N'Madagascar', N'MG', N'MDG', NULL, N'Antananarivo', NULL, NULL, N'MG', 1300, 1),
  (N'مالاوی', N'Malawi', N'MW', N'MWI', NULL, N'Lilongwe', NULL, NULL, N'MW', 1310, 1),
  (N'مالزی', N'Malaysia', N'MY', N'MYS', NULL, N'Kuala Lumpur', NULL, NULL, N'MY', 1320, 1),
  (N'مالدیو', N'Maldives', N'MV', N'MDV', NULL, N'Male', NULL, NULL, N'MV', 1330, 1),
  (N'مالی', N'Mali', N'ML', N'MLI', NULL, N'Bamako', NULL, NULL, N'ML', 1340, 1),
  (N'مالت', N'Malta', N'MT', N'MLT', NULL, N'Valletta', NULL, NULL, N'MT', 1350, 1),
  (N'جزایر مارشال', N'Marshall Islands', N'MH', N'MHL', NULL, N'Majuro', NULL, NULL, N'MH', 1360, 1),
  (N'مارتینیک', N'Martinique', N'MQ', N'MTQ', NULL, N'Fort-de-France', NULL, NULL, N'MQ', 1370, 1),
  (N'موریتانی', N'Mauritania', N'MR', N'MRT', NULL, N'Nouakchott', NULL, NULL, N'MR', 1380, 1),
  (N'موریس', N'Mauritius', N'MU', N'MUS', NULL, N'Port Louis', NULL, NULL, N'MU', 1390, 1),
  (N'مایوت', N'Mayotte', N'YT', N'MYT', NULL, N'Mamoudzou', NULL, NULL, N'YT', 1400, 1),
  (N'مکزیک', N'Mexico', N'MX', N'MEX', NULL, N'Mexico City', NULL, NULL, N'MX', 1410, 1),
  (N'میکرونزی', N'Micronesia', N'FM', N'FSM', NULL, N'Palikir', NULL, NULL, N'FM', 1420, 1),
  (N'مولداوی', N'Moldova', N'MD', N'MDA', NULL, N'Chisinau', NULL, NULL, N'MD', 1430, 1),
  (N'موناکو', N'Monaco', N'MC', N'MCO', NULL, N'Monaco', NULL, NULL, N'MC', 1440, 1),
  (N'مغولستان', N'Mongolia', N'MN', N'MNG', NULL, N'Ulan Bator', NULL, NULL, N'MN', 1450, 1),
  (N'مونته‌نگرو', N'Montenegro', N'ME', N'MNE', NULL, N'Podgorica', NULL, NULL, N'ME', 1460, 1),
  (N'مونت‌سرات', N'Montserrat', N'MS', N'MSR', NULL, N'Plymouth', NULL, NULL, N'MS', 1470, 1),
  (N'مراکش', N'Morocco', N'MA', N'MAR', NULL, N'Rabat', NULL, NULL, N'MA', 1480, 1),
  (N'موزامبیک', N'Mozambique', N'MZ', N'MOZ', NULL, N'Maputo', NULL, NULL, N'MZ', 1490, 1),
  (N'میانمار (برمه)', N'Myanmar', N'MM', N'MMR', NULL, N'Nay Pyi Taw', NULL, NULL, N'MM', 1500, 1),
  (N'نامیبیا', N'Namibia', N'NA', N'NAM', NULL, N'Windhoek', NULL, NULL, N'NA', 1510, 1),
  (N'نائورو', N'Nauru', N'NR', N'NRU', NULL, N'Yaren', NULL, NULL, N'NR', 1520, 1),
  (N'نپال', N'Nepal', N'NP', N'NPL', NULL, N'Kathmandu', NULL, NULL, N'NP', 1530, 1),
  (N'هلند', N'Netherlands', N'NL', N'NLD', NULL, N'Amsterdam', NULL, NULL, N'NL', 1540, 1),
  (N'کالدونیای جدید', N'New Caledonia', N'NC', N'NCL', NULL, N'Noumea', NULL, NULL, N'NC', 1550, 1),
  (N'نیوزیلند', N'New Zealand', N'NZ', N'NZL', NULL, N'Wellington', NULL, NULL, N'NZ', 1560, 1),
  (N'نیکاراگوئه', N'Nicaragua', N'NI', N'NIC', NULL, N'Managua', NULL, NULL, N'NI', 1570, 1),
  (N'نیجر', N'Niger', N'NE', N'NER', NULL, N'Niamey', NULL, NULL, N'NE', 1580, 1),
  (N'نیجریه', N'Nigeria', N'NG', N'NGA', NULL, N'Abuja', NULL, NULL, N'NG', 1590, 1),
  (N'نیوئه', N'Niue', N'NU', N'NIU', NULL, N'Alofi', NULL, NULL, N'NU', 1600, 1),
  (N'جزیرهٔ نورفولک', N'Norfolk Island', N'NF', N'NFK', NULL, N'Kingston', NULL, NULL, N'NF', 1610, 1),
  (N'کرهٔ شمالی', N'North Korea', N'KP', N'PRK', NULL, N'Pyongyang', NULL, NULL, N'KP', 1620, 1),
  (N'جزایر ماریانای شمالی', N'Northern Mariana Islands', N'MP', N'MNP', NULL, N'Saipan', NULL, NULL, N'MP', 1630, 1),
  (N'نروژ', N'Norway', N'NO', N'NOR', NULL, N'Oslo', NULL, NULL, N'NO', 1640, 1),
  (N'عمان', N'Oman', N'OM', N'OMN', NULL, N'Muscat', NULL, NULL, N'OM', 1650, 1),
  (N'پاکستان', N'Pakistan', N'PK', N'PAK', NULL, N'Islamabad', NULL, NULL, N'PK', 1660, 1),
  (N'پالائو', N'Palau', N'PW', N'PLW', NULL, N'Melekeok', NULL, NULL, N'PW', 1670, 1),
  (N'سرزمین‌های فلسطینی', N'Palestinian Territory', N'PS', N'PSE', NULL, N'East Jerusalem', NULL, NULL, N'PS', 1680, 1),
  (N'پاناما', N'Panama', N'PA', N'PAN', NULL, N'Panama City', NULL, NULL, N'PA', 1690, 1),
  (N'پاپوا گینهٔ نو', N'Papua New Guinea', N'PG', N'PNG', NULL, N'Port Moresby', NULL, NULL, N'PG', 1700, 1),
  (N'پاراگوئه', N'Paraguay', N'PY', N'PRY', NULL, N'Asuncion', NULL, NULL, N'PY', 1710, 1),
  (N'پرو', N'Peru', N'PE', N'PER', NULL, N'Lima', NULL, NULL, N'PE', 1720, 1),
  (N'فیلیپین', N'Philippines', N'PH', N'PHL', NULL, N'Manila', NULL, NULL, N'PH', 1730, 1),
  (N'جزایر پیت‌کرن', N'Pitcairn', N'PN', N'PCN', NULL, N'Adamstown', NULL, NULL, N'PN', 1740, 1),
  (N'لهستان', N'Poland', N'PL', N'POL', NULL, N'Warsaw', NULL, NULL, N'PL', 1750, 1),
  (N'پرتغال', N'Portugal', N'PT', N'PRT', NULL, N'Lisbon', NULL, NULL, N'PT', 1760, 1),
  (N'پورتوریکو', N'Puerto Rico', N'PR', N'PRI', NULL, N'San Juan', NULL, NULL, N'PR', 1770, 1),
  (N'قطر', N'Qatar', N'QA', N'QAT', NULL, N'Doha', NULL, NULL, N'QA', 1780, 1),
  (N'رئونیون', N'Réunion', N'RE', N'REU', NULL, N'Saint-Denis', NULL, NULL, N'RE', 1790, 1),
  (N'رومانی', N'Romania', N'RO', N'ROU', NULL, N'Bucharest', NULL, NULL, N'RO', 1800, 1),
  (N'روسیه', N'Russia', N'RU', N'RUS', NULL, N'Moscow', NULL, NULL, N'RU', 1810, 1),
  (N'رواندا', N'Rwanda', N'RW', N'RWA', NULL, N'Kigali', NULL, NULL, N'RW', 1820, 1),
  (N'سن بارتلمی', N'Saint Barthelemy', N'BL', N'BLM', NULL, N'Gustavia', NULL, NULL, N'BL', 1830, 1),
  (N'سنت هلن', N'Saint Helena', N'SH', N'SHN', NULL, N'Jamestown', NULL, NULL, N'SH', 1840, 1),
  (N'سنت کیتس و نویس', N'Saint Kitts and Nevis', N'KN', N'KNA', NULL, N'Basseterre', NULL, NULL, N'KN', 1850, 1),
  (N'سنت لوسیا', N'Saint Lucia', N'LC', N'LCA', NULL, N'Castries', NULL, NULL, N'LC', 1860, 1),
  (N'سنت مارتین', N'Saint Martin', N'MF', N'MAF', NULL, N'Marigot', NULL, NULL, N'MF', 1870, 1),
  (N'سن پیر و میکلن', N'Saint Pierre and Miquelon', N'PM', N'SPM', NULL, N'Saint-Pierre', NULL, NULL, N'PM', 1880, 1),
  (N'سنت وینسنت و گرنادین', N'Saint Vincent and the Grenadines', N'VC', N'VCT', NULL, N'Kingstown', NULL, NULL, N'VC', 1890, 1),
  (N'ساموآ', N'Samoa', N'WS', N'WSM', NULL, N'Apia', NULL, NULL, N'WS', 1900, 1),
  (N'سان‌مارینو', N'San Marino', N'SM', N'SMR', NULL, N'San Marino', NULL, NULL, N'SM', 1910, 1),
  (N'سائوتومه و پرینسیپ', N'Sao Tome and Principe', N'ST', N'STP', NULL, N'Sao Tome', NULL, NULL, N'ST', 1920, 1),
  (N'عربستان سعودی', N'Saudi Arabia', N'SA', N'SAU', NULL, N'Riyadh', NULL, NULL, N'SA', 1930, 1),
  (N'سنگال', N'Senegal', N'SN', N'SEN', NULL, N'Dakar', NULL, NULL, N'SN', 1940, 1),
  (N'صربستان', N'Serbia', N'RS', N'SRB', NULL, N'Belgrade', NULL, NULL, N'RS', 1950, 1),
  (N'سیشل', N'Seychelles', N'SC', N'SYC', NULL, N'Victoria', NULL, NULL, N'SC', 1960, 1),
  (N'سیرالئون', N'Sierra Leone', N'SL', N'SLE', NULL, N'Freetown', NULL, NULL, N'SL', 1970, 1),
  (N'سنگاپور', N'Singapore', N'SG', N'SGP', NULL, N'Singapur', NULL, NULL, N'SG', 1980, 1),
  (N'سنت مارتن', N'Sint Maarten', N'SX', N'SXM', NULL, N'Philipsburg', NULL, NULL, N'SX', 1990, 1),
  (N'اسلواکی', N'Slovakia', N'SK', N'SVK', NULL, N'Bratislava', NULL, NULL, N'SK', 2000, 1),
  (N'اسلوونی', N'Slovenia', N'SI', N'SVN', NULL, N'Ljubljana', NULL, NULL, N'SI', 2010, 1),
  (N'جزایر سلیمان', N'Solomon Islands', N'SB', N'SLB', NULL, N'Honiara', NULL, NULL, N'SB', 2020, 1),
  (N'سومالی', N'Somalia', N'SO', N'SOM', NULL, N'Mogadishu', NULL, NULL, N'SO', 2030, 1),
  (N'افریقای جنوبی', N'South Africa', N'ZA', N'ZAF', NULL, N'Pretoria', NULL, NULL, N'ZA', 2040, 1),
  (N'جورجیای جنوبی و جزایر ساندویچ جنوبی', N'South Georgia and the South Sandwich Islands', N'GS', N'SGS', NULL, N'Grytviken', NULL, NULL, N'GS', 2050, 1),
  (N'کرهٔ جنوبی', N'South Korea', N'KR', N'KOR', NULL, N'Seoul', NULL, NULL, N'KR', 2060, 1),
  (N'سودان جنوبی', N'South Sudan', N'SS', N'SSD', NULL, N'Juba', NULL, NULL, N'SS', 2070, 1),
  (N'اسپانیا', N'Spain', N'ES', N'ESP', NULL, N'Madrid', NULL, NULL, N'ES', 2080, 1),
  (N'سری‌لانکا', N'Sri Lanka', N'LK', N'LKA', NULL, N'Colombo', NULL, NULL, N'LK', 2090, 1),
  (N'سودان', N'Sudan', N'SD', N'SDN', NULL, N'Khartoum', NULL, NULL, N'SD', 2100, 1),
  (N'سورینام', N'Suriname', N'SR', N'SUR', NULL, N'Paramaribo', NULL, NULL, N'SR', 2110, 1),
  (N'سوالبارد و یان ماین', N'Svalbard and Jan Mayen', N'SJ', N'SJM', NULL, N'Longyearbyen', NULL, NULL, N'SJ', 2120, 1),
  (N'اسواتینی', N'Swaziland', N'SZ', N'SWZ', NULL, N'Mbabane', NULL, NULL, N'SZ', 2130, 1),
  (N'سوئد', N'Sweden', N'SE', N'SWE', NULL, N'Stockholm', NULL, NULL, N'SE', 2140, 1),
  (N'سوئیس', N'Switzerland', N'CH', N'CHE', NULL, N'Berne', NULL, NULL, N'CH', 2150, 1),
  (N'سوریه', N'Syria', N'SY', N'SYR', NULL, N'Damascus', NULL, NULL, N'SY', 2160, 1),
  (N'تایوان', N'Taiwan', N'TW', N'TWN', NULL, N'Taipei', NULL, NULL, N'TW', 2170, 1),
  (N'تاجیکستان', N'Tajikistan', N'TJ', N'TJK', NULL, N'Dushanbe', NULL, NULL, N'TJ', 2180, 1),
  (N'تانزانیا', N'Tanzania', N'TZ', N'TZA', NULL, N'Dodoma', NULL, NULL, N'TZ', 2190, 1),
  (N'تایلند', N'Thailand', N'TH', N'THA', NULL, N'Bangkok', NULL, NULL, N'TH', 2200, 1),
  (N'تیمور-لسته', N'Timor-Leste', N'TL', N'TLS', NULL, N'Dili', NULL, NULL, N'TL', 2210, 1),
  (N'توگو', N'Togo', N'TG', N'TGO', NULL, N'Lome', NULL, NULL, N'TG', 2220, 1),
  (N'توکلائو', N'Tokelau', N'TK', N'TKL', NULL, NULL, NULL, NULL, N'TK', 2230, 1),
  (N'تونگا', N'Tonga', N'TO', N'TON', NULL, N'Nuku''alofa', NULL, NULL, N'TO', 2240, 1),
  (N'ترینیداد و توباگو', N'Trinidad and Tobago', N'TT', N'TTO', NULL, N'Port of Spain', NULL, NULL, N'TT', 2250, 1),
  (N'تونس', N'Tunisia', N'TN', N'TUN', NULL, N'Tunis', NULL, NULL, N'TN', 2260, 1),
  (N'ترکیه', N'Turkey', N'TR', N'TUR', NULL, N'Ankara', NULL, NULL, N'TR', 2270, 1),
  (N'ترکمنستان', N'Turkmenistan', N'TM', N'TKM', NULL, N'Ashgabat', NULL, NULL, N'TM', 2280, 1),
  (N'جزایر تورکس و کایکوس', N'Turks and Caicos Islands', N'TC', N'TCA', NULL, N'Cockburn Town', NULL, NULL, N'TC', 2290, 1),
  (N'تووالو', N'Tuvalu', N'TV', N'TUV', NULL, N'Funafuti', NULL, NULL, N'TV', 2300, 1),
  (N'جزایر ویرجین ایالات متحده', N'U.S. Virgin Islands', N'VI', N'VIR', NULL, N'Charlotte Amalie', NULL, NULL, N'VI', 2310, 1),
  (N'اوگاندا', N'Uganda', N'UG', N'UGA', NULL, N'Kampala', NULL, NULL, N'UG', 2320, 1),
  (N'اوکراین', N'Ukraine', N'UA', N'UKR', NULL, N'Kiev', NULL, NULL, N'UA', 2330, 1),
  (N'امارات متحدهٔ عربی', N'United Arab Emirates', N'AE', N'ARE', NULL, N'Abu Dhabi', NULL, NULL, N'AE', 2340, 1),
  (N'بریتانیا', N'United Kingdom', N'GB', N'GBR', NULL, N'London', NULL, NULL, N'GB', 2350, 1),
  (N'ایالات متحده', N'United States', N'US', N'USA', NULL, N'Washington', NULL, NULL, N'US', 2360, 1),
  (N'جزایر دورافتادهٔ ایالات متحده', N'United States Minor Outlying Islands', N'UM', N'UMI', NULL, NULL, NULL, NULL, N'UM', 2370, 1),
  (N'اروگوئه', N'Uruguay', N'UY', N'URY', NULL, N'Montevideo', NULL, NULL, N'UY', 2380, 1),
  (N'ازبکستان', N'Uzbekistan', N'UZ', N'UZB', NULL, N'Tashkent', NULL, NULL, N'UZ', 2390, 1),
  (N'وانواتو', N'Vanuatu', N'VU', N'VUT', NULL, N'Port Vila', NULL, NULL, N'VU', 2400, 1),
  (N'واتیکان', N'Vatican', N'VA', N'VAT', NULL, N'Vatican City', NULL, NULL, N'VA', 2410, 1),
  (N'ونزوئلا', N'Venezuela', N'VE', N'VEN', NULL, N'Caracas', NULL, NULL, N'VE', 2420, 1),
  (N'ویتنام', N'Vietnam', N'VN', N'VNM', NULL, N'Hanoi', NULL, NULL, N'VN', 2430, 1),
  (N'والیس و فوتونا', N'Wallis and Futuna', N'WF', N'WLF', NULL, N'Mata Utu', NULL, NULL, N'WF', 2440, 1),
  (N'صحرای غربی', N'Western Sahara', N'EH', N'ESH', NULL, N'El-Aaiun', NULL, NULL, N'EH', 2450, 1),
  (N'یمن', N'Yemen', N'YE', N'YEM', NULL, N'Sanaa', NULL, NULL, N'YE', 2460, 1),
  (N'زامبیا', N'Zambia', N'ZM', N'ZMB', NULL, N'Lusaka', NULL, NULL, N'ZM', 2470, 1),
  (N'زیمبابوه', N'Zimbabwe', N'ZW', N'ZWE', NULL, N'Harare', NULL, NULL, N'ZW', 2480, 1)
) AS source (name_fa, name_en, iso2, iso3, phone_code, capital, currency_code, timezone_default, flag, sort_order, accuracy)
ON target.iso2 = source.iso2
WHEN MATCHED THEN
  UPDATE SET
    name_fa = source.name_fa,
    name_en = source.name_en,
    iso3 = source.iso3,
    phone_code = source.phone_code,
    capital = source.capital,
    currency_code = source.currency_code,
    timezone_default = source.timezone_default,
    flag = source.flag,
    sort_order = source.sort_order,
    accuracy = source.accuracy,
    modified_at = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
  INSERT (name_fa, name_en, iso2, iso3, phone_code, capital, currency_code, timezone_default, flag, sort_order, accuracy)
  VALUES (source.name_fa, source.name_en, source.iso2, source.iso3, source.phone_code, source.capital, source.currency_code, source.timezone_default, source.flag, source.sort_order, source.accuracy);
GO
